"""SVG writer for CardBoxGen panels."""

from __future__ import annotations

import html
import json
import textwrap
from typing import Dict, List, Optional, Tuple

from .geometry import fmt, polygon_to_path_with_tabs, polyline_to_path
from .layout import arrange_panels
from .panels import Panel
from .version import __version__


def try_import_pyclipper():
    try:
        import pyclipper  # type: ignore

        return pyclipper
    except Exception:
        return None


def offset_polygon_pyclipper(points, delta: float):
    pc = try_import_pyclipper()
    if pc is None or len(points) < 3:
        return None
    scale = 1000.0
    path = [(int(round(x * scale)), int(round(y * scale))) for x, y in points]
    co = pc.PyclipperOffset()
    co.AddPath(path, pc.JT_MITER, pc.ET_CLOSEDPOLYGON)
    res = co.Execute(delta * scale)
    if not res:
        return None

    def area_i(poly):
        a = 0
        for (x0, y0), (x1, y1) in zip(poly, poly[1:] + poly[:1]):
            a += x0 * y1 - x1 * y0
        return abs(a)

    best = max(res, key=area_i)
    return [(p[0] / scale, p[1] / scale) for p in best]


def svg_header(width: float, height: float) -> str:
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        f"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{fmt(width)}mm\" height=\"{fmt(height)}mm\" viewBox=\"0 0 {fmt(width)} {fmt(height)}\">\n"
        f"  <desc>Generated by cardboxgen v{html.escape(__version__)}</desc>\n"
    )


def svg_footer() -> str:
    return "</svg>\n"


def svg_layer_styles(*, stroke_mm: float = 0.2) -> str:
    s = max(0.001, float(stroke_mm))
    return (
        "  <style>\n"
        f"    .cut {{ fill: none; stroke: #ff0000; stroke-width: {fmt(s)}; }}\n"
        f"    .score {{ fill: none; stroke: #0000ff; stroke-width: {fmt(s)}; stroke-dasharray: 2 2; }}\n"
        f"    .engrave {{ fill: none; stroke: #000000; stroke-width: {fmt(s)}; }}\n"
        "    .text { fill: #000000; font-family: Arial, sans-serif; font-size: 4px; }\n"
        "  </style>\n"
    )


def make_svg(
    panels: List[Panel],
    *,
    meta: Dict[str, object],
    sheet_width: float = 320.0,
    labels: bool = True,
    offset_kerf: bool = False,
    kerf_mm: float = 0.2,
    layout_margin_mm: float = 10.0,
    layout_padding_mm: float = 12.0,
    stroke_mm: float = 0.2,
    holding_tabs: bool = False,
    tab_width_mm: float = 2.0,
) -> str:
    placed, width, height = arrange_panels(
        panels,
        sheet_width=sheet_width,
        margin=layout_margin_mm,
        gap=layout_padding_mm,
    )
    meta_comment = "\n".join(textwrap.wrap(json.dumps(meta, ensure_ascii=False, sort_keys=True), width=120))
    out = [svg_header(width, height), svg_layer_styles(stroke_mm=stroke_mm)]
    out.append(f"  <metadata>{html.escape(json.dumps(meta, ensure_ascii=False, sort_keys=True))}</metadata>\n")
    out.append(f"  <!-- meta: {html.escape(meta_comment)} -->\n")

    label_items: List[Tuple[str, float, float]] = []

    out.append('  <g id="CUT" class="cut">\n')
    for item in placed:
        panel = item.panel
        outline = panel.outline
        if offset_kerf:
            off = offset_polygon_pyclipper(outline, float(kerf_mm) / 2.0)
            if off is not None:
                outline = off
        out.append(f'    <g id="{html.escape(panel.name)}" transform="translate({fmt(item.x)},{fmt(item.y)})">\n')
        if holding_tabs:
            d = polygon_to_path_with_tabs(outline, tab_width_mm=tab_width_mm)
        else:
            d = polyline_to_path(outline, close=True)
        out.append(f'      <path d="{html.escape(d)}"/>\n')
        for cutout in panel.cutouts:
            d2 = cutout.to_svg_d()
            if d2:
                out.append(f'      <path d="{html.escape(d2)}"/>\n')
        out.append("    </g>\n")
        if labels:
            for text, (tx, ty) in panel.labels:
                label_items.append((text, item.x + tx, item.y + ty))
    out.append("  </g>\n")

    out.append('  <g id="SCORE" class="score">\n')
    for item in placed:
        panel = item.panel
        if not panel.score_paths:
            continue
        out.append(f'    <g id="{html.escape(panel.name)}_SCORE" transform="translate({fmt(item.x)},{fmt(item.y)})">\n')
        for score in panel.score_paths:
            d = score.to_svg_d()
            if d:
                out.append(f'      <path d="{html.escape(d)}"/>\n')
        out.append("    </g>\n")
    out.append("  </g>\n")

    out.append('  <g id="ENGRAVE" class="engrave">\n')
    if labels:
        for text, tx, ty in label_items:
            out.append(f'    <text class="text" x="{fmt(tx)}" y="{fmt(ty)}">{html.escape(str(text))}</text>\n')
    out.append("  </g>\n")

    out.append(svg_footer())
    return "".join(out)


def make_diagnostic_svg(*, messages: List[Dict[str, object]], meta: Dict[str, object], width: float = 220.0, height: float = 140.0) -> str:
    out = [svg_header(width, height), svg_layer_styles(stroke_mm=0.2)]
    out.append(f"  <metadata>{html.escape(json.dumps(meta, ensure_ascii=False, sort_keys=True))}</metadata>\n")
    out.append('  <g id="DIAGNOSTIC" fill="black" font-family="Arial, sans-serif" font-size="5">\n')
    out.append('    <text x="10" y="16" font-size="8" fill="#b00020">NOT EXPORTABLE</text>\n')
    out.append('    <text x="10" y="28">CardBoxGen validation blocked this cut file.</text>\n')
    y = 42
    for msg in messages[:8]:
        code = html.escape(str(msg.get("code", "")))
        text = html.escape(str(msg.get("message", "")))
        out.append(f'    <text x="10" y="{fmt(y)}">{code}: {text[:120]}</text>\n')
        y += 9
    out.append("  </g>\n")
    out.append(svg_footer())
    return "".join(out)
