#!/usr/bin/env python3
"""Build the single-file Pyodide API bundle used by docs/app.js."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

MODULES = [
    "cardboxgen.version",
    "cardboxgen.geometry",
    "cardboxgen.models",
    "cardboxgen.joints",
    "cardboxgen.panels",
    "cardboxgen.layout",
    "cardboxgen.svg",
    "cardboxgen.presets.common",
    "cardboxgen.presets.tray",
    "cardboxgen.presets.dispenser",
    "cardboxgen.presets.window_box",
    "cardboxgen.presets.box_lid",
    "cardboxgen.presets.divider_rack",
    "cardboxgen.presets.card_shoe",
    "cardboxgen.presets.candy_machine",
    "cardboxgen.presets.calibration",
    "cardboxgen.presets",
    "cardboxgen.api",
    "cardboxgen",
]


def module_path(root: Path, module_name: str) -> Path:
    parts = module_name.split(".")
    if module_name == "cardboxgen":
        return root / "cardboxgen" / "__init__.py"
    if parts[-1] == "presets":
        return root / "cardboxgen" / "presets" / "__init__.py"
    return root.joinpath(*parts).with_suffix(".py")


def build_bundle(root: Path) -> str:
    chunks = [
        "# Auto-generated by tools/sync_docs.py. Do not edit by hand.\n",
        "from __future__ import annotations\n\n",
        "import sys\nimport types\n\n",
        "pkg = types.ModuleType('cardboxgen')\n",
        "pkg.__path__ = []\n",
        "sys.modules['cardboxgen'] = pkg\n",
        "presets_pkg = types.ModuleType('cardboxgen.presets')\n",
        "presets_pkg.__path__ = []\n",
        "sys.modules['cardboxgen.presets'] = presets_pkg\n",
        "setattr(pkg, 'presets', presets_pkg)\n\n",
        "def _load_module(name, source):\n",
        "    mod = sys.modules.get(name) or types.ModuleType(name)\n",
        "    mod.__file__ = '<cardboxgen_bundle>'\n",
        "    if name in {'cardboxgen', 'cardboxgen.presets'}:\n",
        "        mod.__package__ = name\n",
        "        mod.__path__ = []\n",
        "    else:\n",
        "        mod.__package__ = name.rpartition('.')[0]\n",
        "    sys.modules[name] = mod\n",
        "    parent_name, _, attr = name.rpartition('.')\n",
        "    if parent_name:\n",
        "        parent = sys.modules[parent_name]\n",
        "        setattr(parent, attr, mod)\n",
        "    exec(compile(source, name, 'exec'), mod.__dict__)\n",
        "    return mod\n\n",
    ]
    for module_name in MODULES:
        src = module_path(root, module_name).read_text(encoding="utf-8")
        chunks.append(f"_load_module({module_name!r}, {src!r})\n\n")
    chunks.append("from cardboxgen.api import generate_svg\n")
    chunks.append("from cardboxgen.version import __version__\n")
    chunks.append("__all__ = ['__version__', 'generate_svg']\n")
    return "".join(chunks)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="Fail if docs/cardboxgen_bundle.py is stale.")
    args = ap.parse_args(argv)
    root = Path(__file__).resolve().parent.parent
    dst = root / "docs" / "cardboxgen_bundle.py"
    content = build_bundle(root)
    if args.check:
        if not dst.exists():
            raise SystemExit("docs/cardboxgen_bundle.py is missing; run python tools/sync_docs.py")
        old = dst.read_text(encoding="utf-8")
        if old != content:
            diff = "\n".join(difflib.unified_diff(old.splitlines(), content.splitlines(), fromfile=str(dst), tofile="generated", lineterm=""))
            raise SystemExit(f"docs/cardboxgen_bundle.py is stale; run python tools/sync_docs.py\n{diff[:4000]}")
        print("docs/cardboxgen_bundle.py is fresh")
        return 0
    dst.write_text(content, encoding="utf-8")
    print(f"Synced package API bundle -> {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
